# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.update_user_details import UpdateUserDetails
from ..types.user_details import UserDetails
from .raw_client import AsyncRawMyProfileClient, RawMyProfileClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MyProfileClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMyProfileClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMyProfileClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMyProfileClient
        """
        return self._raw_client

    def get_my_profile(self, *, request_options: typing.Optional[RequestOptions] = None) -> UserDetails:
        """
        Returns your profile and metadata

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserDetails
            User Details

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_profile.get_my_profile()
        """
        _response = self._raw_client.get_my_profile(request_options=request_options)
        return _response.data

    def update_my_profile(
        self, *, user: UpdateUserDetails, request_options: typing.Optional[RequestOptions] = None
    ) -> UserDetails:
        """
        Updates your profile and metadata

        Parameters
        ----------
        user : UpdateUserDetails

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserDetails
            Updated User Details

        Examples
        --------
        from thenvoi_client_rest import RestClient, UpdateUserDetails

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_profile.update_my_profile(
            user=UpdateUserDetails(),
        )
        """
        _response = self._raw_client.update_my_profile(user=user, request_options=request_options)
        return _response.data


class AsyncMyProfileClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMyProfileClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMyProfileClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMyProfileClient
        """
        return self._raw_client

    async def get_my_profile(self, *, request_options: typing.Optional[RequestOptions] = None) -> UserDetails:
        """
        Returns your profile and metadata

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserDetails
            User Details

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_profile.get_my_profile()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_my_profile(request_options=request_options)
        return _response.data

    async def update_my_profile(
        self, *, user: UpdateUserDetails, request_options: typing.Optional[RequestOptions] = None
    ) -> UserDetails:
        """
        Updates your profile and metadata

        Parameters
        ----------
        user : UpdateUserDetails

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserDetails
            Updated User Details

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient, UpdateUserDetails

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_profile.update_my_profile(
                user=UpdateUserDetails(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_my_profile(user=user, request_options=request_options)
        return _response.data
