# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chat_room_request import ChatRoomRequest
from ..types.chat_room_update_request import ChatRoomUpdateRequest
from .raw_client import AsyncRawChatRoomsClient, RawChatRoomsClient
from .types.create_chat_response import CreateChatResponse
from .types.get_chat_response import GetChatResponse
from .types.list_chats_request_status import ListChatsRequestStatus
from .types.list_chats_request_type import ListChatsRequestType
from .types.list_chats_response import ListChatsResponse
from .types.update_chat_response import UpdateChatResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChatRoomsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChatRoomsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChatRoomsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChatRoomsClient
        """
        return self._raw_client

    def list_chats(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        status: typing.Optional[ListChatsRequestStatus] = None,
        type: typing.Optional[ListChatsRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChatsResponse:
        """
        Lists chat rooms with optional filtering and pagination

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        status : typing.Optional[ListChatsRequestStatus]
            Filter by status

        type : typing.Optional[ListChatsRequestType]
            Filter by type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChatsResponse
            Chat Rooms

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_rooms.list_chats(
            page=1,
            per_page=1,
            status="active",
            type="direct",
        )
        """
        _response = self._raw_client.list_chats(
            page=page, per_page=per_page, status=status, type=type, request_options=request_options
        )
        return _response.data

    def create_chat(
        self, *, chat: ChatRoomRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateChatResponse:
        """
        Creates a new chat room

        Parameters
        ----------
        chat : ChatRoomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateChatResponse
            Created Chat Room

        Examples
        --------
        from thenvoi_client_rest import ChatRoomRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_rooms.create_chat(
            chat=ChatRoomRequest(
                owner_id="owner_id",
                owner_type="User",
                status="active",
                title="title",
                type="direct",
            ),
        )
        """
        _response = self._raw_client.create_chat(chat=chat, request_options=request_options)
        return _response.data

    def get_chat(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetChatResponse:
        """
        Gets a specific chat room by ID. Returns 404 if the room doesn't exist or if you're not a participant (security-first: doesn't leak room existence).

        Parameters
        ----------
        id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetChatResponse
            Chat Room

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_rooms.get_chat(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.get_chat(id, request_options=request_options)
        return _response.data

    def update_chat(
        self, id: str, *, chat: ChatRoomUpdateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateChatResponse:
        """
        Updates a specific chat room (supports partial updates). Only the room owner can update. Returns 404 if room doesn't exist or you're not a participant (security-first), 403 if you're a participant but not the owner.

        Parameters
        ----------
        id : str
            Chat Room ID

        chat : ChatRoomUpdateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateChatResponse
            Updated Chat Room

        Examples
        --------
        from thenvoi_client_rest import ChatRoomUpdateRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_rooms.update_chat(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            chat=ChatRoomUpdateRequest(),
        )
        """
        _response = self._raw_client.update_chat(id, chat=chat, request_options=request_options)
        return _response.data

    def delete_chat(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Deletes a specific chat room. Only the room owner can delete. Returns 404 if room doesn't exist or you're not a participant (security-first), 403 if you're a participant but not the owner.

        Parameters
        ----------
        id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            No Content

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_rooms.delete_chat(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.delete_chat(id, request_options=request_options)
        return _response.data


class AsyncChatRoomsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChatRoomsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChatRoomsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChatRoomsClient
        """
        return self._raw_client

    async def list_chats(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        status: typing.Optional[ListChatsRequestStatus] = None,
        type: typing.Optional[ListChatsRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChatsResponse:
        """
        Lists chat rooms with optional filtering and pagination

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        status : typing.Optional[ListChatsRequestStatus]
            Filter by status

        type : typing.Optional[ListChatsRequestType]
            Filter by type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChatsResponse
            Chat Rooms

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_rooms.list_chats(
                page=1,
                per_page=1,
                status="active",
                type="direct",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_chats(
            page=page, per_page=per_page, status=status, type=type, request_options=request_options
        )
        return _response.data

    async def create_chat(
        self, *, chat: ChatRoomRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateChatResponse:
        """
        Creates a new chat room

        Parameters
        ----------
        chat : ChatRoomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateChatResponse
            Created Chat Room

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient, ChatRoomRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_rooms.create_chat(
                chat=ChatRoomRequest(
                    owner_id="owner_id",
                    owner_type="User",
                    status="active",
                    title="title",
                    type="direct",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_chat(chat=chat, request_options=request_options)
        return _response.data

    async def get_chat(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetChatResponse:
        """
        Gets a specific chat room by ID. Returns 404 if the room doesn't exist or if you're not a participant (security-first: doesn't leak room existence).

        Parameters
        ----------
        id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetChatResponse
            Chat Room

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_rooms.get_chat(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_chat(id, request_options=request_options)
        return _response.data

    async def update_chat(
        self, id: str, *, chat: ChatRoomUpdateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateChatResponse:
        """
        Updates a specific chat room (supports partial updates). Only the room owner can update. Returns 404 if room doesn't exist or you're not a participant (security-first), 403 if you're a participant but not the owner.

        Parameters
        ----------
        id : str
            Chat Room ID

        chat : ChatRoomUpdateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateChatResponse
            Updated Chat Room

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient, ChatRoomUpdateRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_rooms.update_chat(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                chat=ChatRoomUpdateRequest(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_chat(id, chat=chat, request_options=request_options)
        return _response.data

    async def delete_chat(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Deletes a specific chat room. Only the room owner can delete. Returns 404 if room doesn't exist or you're not a participant (security-first), 403 if you're a participant but not the owner.

        Parameters
        ----------
        id : str
            Chat Room ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            No Content

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_rooms.delete_chat(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_chat(id, request_options=request_options)
        return _response.data
