# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawChatParticipantsClient, RawChatParticipantsClient
from .types.add_chat_participant_request_participant import AddChatParticipantRequestParticipant
from .types.add_chat_participant_response import AddChatParticipantResponse
from .types.get_available_chat_participants_request_participant_type import (
    GetAvailableChatParticipantsRequestParticipantType,
)
from .types.get_available_chat_participants_response import GetAvailableChatParticipantsResponse
from .types.list_chat_participants_request_participant_type import ListChatParticipantsRequestParticipantType
from .types.list_chat_participants_response import ListChatParticipantsResponse
from .types.remove_chat_participant_response import RemoveChatParticipantResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChatParticipantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChatParticipantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChatParticipantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChatParticipantsClient
        """
        return self._raw_client

    def get_available_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: GetAvailableChatParticipantsRequestParticipantType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAvailableChatParticipantsResponse:
        """
        Returns a list of users or agents not currently in the chat room who can be added as participants

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : GetAvailableChatParticipantsRequestParticipantType
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAvailableChatParticipantsResponse
            Available Participants

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_participants.get_available_chat_participants(
            chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            participant_type="User",
        )
        """
        _response = self._raw_client.get_available_chat_participants(
            chat_id, participant_type=participant_type, request_options=request_options
        )
        return _response.data

    def list_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: typing.Optional[ListChatParticipantsRequestParticipantType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChatParticipantsResponse:
        """
        Returns a list of participants in a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : typing.Optional[ListChatParticipantsRequestParticipantType]
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChatParticipantsResponse
            Chat Room Participants

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_participants.list_chat_participants(
            chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            participant_type="User",
        )
        """
        _response = self._raw_client.list_chat_participants(
            chat_id, participant_type=participant_type, request_options=request_options
        )
        return _response.data

    def add_chat_participant(
        self,
        chat_id: str,
        *,
        participant: AddChatParticipantRequestParticipant,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddChatParticipantResponse:
        """
        Adds a new participant to a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant : AddChatParticipantRequestParticipant

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddChatParticipantResponse
            Participant Added

        Examples
        --------
        from thenvoi_client_rest import RestClient
        from thenvoi_client_rest.chat_participants import (
            AddChatParticipantRequestParticipant,
        )

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_participants.add_chat_participant(
            chat_id="chat_id",
            participant=AddChatParticipantRequestParticipant(
                participant_id="participant_id",
                role="owner",
            ),
        )
        """
        _response = self._raw_client.add_chat_participant(
            chat_id, participant=participant, request_options=request_options
        )
        return _response.data

    def remove_chat_participant(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RemoveChatParticipantResponse:
        """
        Removes a participant from a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Participant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveChatParticipantResponse
            Participant Removed

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_participants.remove_chat_participant(
            chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            id="3af67556-0466-4437-9a92-7d7566796457",
        )
        """
        _response = self._raw_client.remove_chat_participant(chat_id, id, request_options=request_options)
        return _response.data


class AsyncChatParticipantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChatParticipantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChatParticipantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChatParticipantsClient
        """
        return self._raw_client

    async def get_available_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: GetAvailableChatParticipantsRequestParticipantType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAvailableChatParticipantsResponse:
        """
        Returns a list of users or agents not currently in the chat room who can be added as participants

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : GetAvailableChatParticipantsRequestParticipantType
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAvailableChatParticipantsResponse
            Available Participants

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_participants.get_available_chat_participants(
                chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                participant_type="User",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_available_chat_participants(
            chat_id, participant_type=participant_type, request_options=request_options
        )
        return _response.data

    async def list_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: typing.Optional[ListChatParticipantsRequestParticipantType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChatParticipantsResponse:
        """
        Returns a list of participants in a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : typing.Optional[ListChatParticipantsRequestParticipantType]
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChatParticipantsResponse
            Chat Room Participants

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_participants.list_chat_participants(
                chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                participant_type="User",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_chat_participants(
            chat_id, participant_type=participant_type, request_options=request_options
        )
        return _response.data

    async def add_chat_participant(
        self,
        chat_id: str,
        *,
        participant: AddChatParticipantRequestParticipant,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddChatParticipantResponse:
        """
        Adds a new participant to a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant : AddChatParticipantRequestParticipant

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddChatParticipantResponse
            Participant Added

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient
        from thenvoi_client_rest.chat_participants import (
            AddChatParticipantRequestParticipant,
        )

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_participants.add_chat_participant(
                chat_id="chat_id",
                participant=AddChatParticipantRequestParticipant(
                    participant_id="participant_id",
                    role="owner",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_chat_participant(
            chat_id, participant=participant, request_options=request_options
        )
        return _response.data

    async def remove_chat_participant(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RemoveChatParticipantResponse:
        """
        Removes a participant from a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Participant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveChatParticipantResponse
            Participant Removed

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_participants.remove_chat_participant(
                chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                id="3af67556-0466-4437-9a92-7d7566796457",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_chat_participant(chat_id, id, request_options=request_options)
        return _response.data
