# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.error import Error
from ..types.validation_error import ValidationError
from .types.add_chat_participant_request_participant import AddChatParticipantRequestParticipant
from .types.add_chat_participant_response import AddChatParticipantResponse
from .types.get_available_chat_participants_request_participant_type import (
    GetAvailableChatParticipantsRequestParticipantType,
)
from .types.get_available_chat_participants_response import GetAvailableChatParticipantsResponse
from .types.list_chat_participants_request_participant_type import ListChatParticipantsRequestParticipantType
from .types.list_chat_participants_response import ListChatParticipantsResponse
from .types.remove_chat_participant_response import RemoveChatParticipantResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawChatParticipantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_available_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: GetAvailableChatParticipantsRequestParticipantType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetAvailableChatParticipantsResponse]:
        """
        Returns a list of users or agents not currently in the chat room who can be added as participants

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : GetAvailableChatParticipantsRequestParticipantType
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetAvailableChatParticipantsResponse]
            Available Participants
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/available-participants",
            method="GET",
            params={
                "participant_type": participant_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetAvailableChatParticipantsResponse,
                    parse_obj_as(
                        type_=GetAvailableChatParticipantsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: typing.Optional[ListChatParticipantsRequestParticipantType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListChatParticipantsResponse]:
        """
        Returns a list of participants in a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : typing.Optional[ListChatParticipantsRequestParticipantType]
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListChatParticipantsResponse]
            Chat Room Participants
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/participants",
            method="GET",
            params={
                "participant_type": participant_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListChatParticipantsResponse,
                    parse_obj_as(
                        type_=ListChatParticipantsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_chat_participant(
        self,
        chat_id: str,
        *,
        participant: AddChatParticipantRequestParticipant,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AddChatParticipantResponse]:
        """
        Adds a new participant to a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant : AddChatParticipantRequestParticipant

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AddChatParticipantResponse]
            Participant Added
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/participants",
            method="POST",
            json={
                "participant": convert_and_respect_annotation_metadata(
                    object_=participant, annotation=AddChatParticipantRequestParticipant, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AddChatParticipantResponse,
                    parse_obj_as(
                        type_=AddChatParticipantResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def remove_chat_participant(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[RemoveChatParticipantResponse]:
        """
        Removes a participant from a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Participant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RemoveChatParticipantResponse]
            Participant Removed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/participants/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RemoveChatParticipantResponse,
                    parse_obj_as(
                        type_=RemoveChatParticipantResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawChatParticipantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_available_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: GetAvailableChatParticipantsRequestParticipantType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetAvailableChatParticipantsResponse]:
        """
        Returns a list of users or agents not currently in the chat room who can be added as participants

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : GetAvailableChatParticipantsRequestParticipantType
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetAvailableChatParticipantsResponse]
            Available Participants
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/available-participants",
            method="GET",
            params={
                "participant_type": participant_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetAvailableChatParticipantsResponse,
                    parse_obj_as(
                        type_=GetAvailableChatParticipantsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_chat_participants(
        self,
        chat_id: str,
        *,
        participant_type: typing.Optional[ListChatParticipantsRequestParticipantType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListChatParticipantsResponse]:
        """
        Returns a list of participants in a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant_type : typing.Optional[ListChatParticipantsRequestParticipantType]
            Filter by participant type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListChatParticipantsResponse]
            Chat Room Participants
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/participants",
            method="GET",
            params={
                "participant_type": participant_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListChatParticipantsResponse,
                    parse_obj_as(
                        type_=ListChatParticipantsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_chat_participant(
        self,
        chat_id: str,
        *,
        participant: AddChatParticipantRequestParticipant,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AddChatParticipantResponse]:
        """
        Adds a new participant to a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        participant : AddChatParticipantRequestParticipant

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AddChatParticipantResponse]
            Participant Added
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/participants",
            method="POST",
            json={
                "participant": convert_and_respect_annotation_metadata(
                    object_=participant, annotation=AddChatParticipantRequestParticipant, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AddChatParticipantResponse,
                    parse_obj_as(
                        type_=AddChatParticipantResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def remove_chat_participant(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[RemoveChatParticipantResponse]:
        """
        Removes a participant from a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Participant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RemoveChatParticipantResponse]
            Participant Removed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/participants/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RemoveChatParticipantResponse,
                    parse_obj_as(
                        type_=RemoveChatParticipantResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
