# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chat_message_request import ChatMessageRequest
from .raw_client import AsyncRawMyChatMessagesClient, RawMyChatMessagesClient
from .types.create_my_chat_message_response import CreateMyChatMessageResponse
from .types.list_my_chat_messages_request_message_type import ListMyChatMessagesRequestMessageType
from .types.list_my_chat_messages_response import ListMyChatMessagesResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MyChatMessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMyChatMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMyChatMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMyChatMessagesClient
        """
        return self._raw_client

    def list_my_chat_messages(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        since: typing.Optional[dt.datetime] = None,
        message_type: typing.Optional[ListMyChatMessagesRequestMessageType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyChatMessagesResponse:
        """
        Returns a paginated list of messages in a chat room where you are a participant.

        Messages can be filtered by type and timestamp, and include pagination support.
        Returns 404 if the chat room doesn't exist or you're not a participant (security-first: doesn't leak room existence).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        since : typing.Optional[dt.datetime]
            Filter messages after this timestamp

        message_type : typing.Optional[ListMyChatMessagesRequestMessageType]
            Filter by message type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyChatMessagesResponse
            Chat Messages

        Examples
        --------
        import datetime

        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_chat_messages.list_my_chat_messages(
            chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            page=1,
            per_page=1,
            since=datetime.datetime.fromisoformat(
                "2025-10-14 15:00:00+00:00",
            ),
            message_type="text",
        )
        """
        _response = self._raw_client.list_my_chat_messages(
            chat_id,
            page=page,
            per_page=per_page,
            since=since,
            message_type=message_type,
            request_options=request_options,
        )
        return _response.data

    def create_my_chat_message(
        self, chat_id: str, *, message: ChatMessageRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateMyChatMessageResponse:
        """
        Creates a new message in a chat room where you are a participant.

        The message will be sent from your user account. You can optionally mention other participants.
        Returns 404 if the chat room doesn't exist or you're not a participant (security-first: doesn't leak room existence).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        message : ChatMessageRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMyChatMessageResponse
            Created Message

        Examples
        --------
        from thenvoi_client_rest import ChatMessageRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_chat_messages.create_my_chat_message(
            chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            message=ChatMessageRequest(
                content="content",
            ),
        )
        """
        _response = self._raw_client.create_my_chat_message(chat_id, message=message, request_options=request_options)
        return _response.data


class AsyncMyChatMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMyChatMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMyChatMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMyChatMessagesClient
        """
        return self._raw_client

    async def list_my_chat_messages(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        since: typing.Optional[dt.datetime] = None,
        message_type: typing.Optional[ListMyChatMessagesRequestMessageType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyChatMessagesResponse:
        """
        Returns a paginated list of messages in a chat room where you are a participant.

        Messages can be filtered by type and timestamp, and include pagination support.
        Returns 404 if the chat room doesn't exist or you're not a participant (security-first: doesn't leak room existence).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        since : typing.Optional[dt.datetime]
            Filter messages after this timestamp

        message_type : typing.Optional[ListMyChatMessagesRequestMessageType]
            Filter by message type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyChatMessagesResponse
            Chat Messages

        Examples
        --------
        import asyncio
        import datetime

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_chat_messages.list_my_chat_messages(
                chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                page=1,
                per_page=1,
                since=datetime.datetime.fromisoformat(
                    "2025-10-14 15:00:00+00:00",
                ),
                message_type="text",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_chat_messages(
            chat_id,
            page=page,
            per_page=per_page,
            since=since,
            message_type=message_type,
            request_options=request_options,
        )
        return _response.data

    async def create_my_chat_message(
        self, chat_id: str, *, message: ChatMessageRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateMyChatMessageResponse:
        """
        Creates a new message in a chat room where you are a participant.

        The message will be sent from your user account. You can optionally mention other participants.
        Returns 404 if the chat room doesn't exist or you're not a participant (security-first: doesn't leak room existence).

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        message : ChatMessageRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMyChatMessageResponse
            Created Message

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient, ChatMessageRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_chat_messages.create_my_chat_message(
                chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                message=ChatMessageRequest(
                    content="content",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_my_chat_message(
            chat_id, message=message, request_options=request_options
        )
        return _response.data
