# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent import Agent
    from .agent_request import AgentRequest
    from .agent_update_request import AgentUpdateRequest
    from .available_participant import AvailableParticipant
    from .available_participant_type import AvailableParticipantType
    from .chat_message import ChatMessage
    from .chat_message_request import ChatMessageRequest
    from .chat_message_request_mentions_item import ChatMessageRequestMentionsItem
    from .chat_message_request_message_type import ChatMessageRequestMessageType
    from .chat_message_request_sender_type import ChatMessageRequestSenderType
    from .chat_participant import ChatParticipant
    from .chat_participant_details import ChatParticipantDetails
    from .chat_participant_details_role import ChatParticipantDetailsRole
    from .chat_participant_details_type import ChatParticipantDetailsType
    from .chat_participant_role import ChatParticipantRole
    from .chat_participant_type import ChatParticipantType
    from .chat_room import ChatRoom
    from .chat_room_request import ChatRoomRequest
    from .chat_room_request_owner_type import ChatRoomRequestOwnerType
    from .chat_room_request_status import ChatRoomRequestStatus
    from .chat_room_request_type import ChatRoomRequestType
    from .chat_room_update_request import ChatRoomUpdateRequest
    from .chat_room_update_request_status import ChatRoomUpdateRequestStatus
    from .error import Error
    from .error_error import ErrorError
    from .health_check import HealthCheck
    from .health_check_services import HealthCheckServices
    from .health_check_services_database import HealthCheckServicesDatabase
    from .health_check_services_oban import HealthCheckServicesOban
    from .not_found_error_body import NotFoundErrorBody
    from .not_found_error_body_error import NotFoundErrorBodyError
    from .task import Task
    from .task_request import TaskRequest
    from .task_status import TaskStatus
    from .test_response import TestResponse
    from .test_response_request_info import TestResponseRequestInfo
    from .thread import Thread
    from .tool import Tool
    from .tool_created_by_type import ToolCreatedByType
    from .tool_request import ToolRequest
    from .tool_update_request import ToolUpdateRequest
    from .update_user_details import UpdateUserDetails
    from .user_details import UserDetails
    from .validation_error import ValidationError
    from .validation_error_error import ValidationErrorError
_dynamic_imports: typing.Dict[str, str] = {
    "Agent": ".agent",
    "AgentRequest": ".agent_request",
    "AgentUpdateRequest": ".agent_update_request",
    "AvailableParticipant": ".available_participant",
    "AvailableParticipantType": ".available_participant_type",
    "ChatMessage": ".chat_message",
    "ChatMessageRequest": ".chat_message_request",
    "ChatMessageRequestMentionsItem": ".chat_message_request_mentions_item",
    "ChatMessageRequestMessageType": ".chat_message_request_message_type",
    "ChatMessageRequestSenderType": ".chat_message_request_sender_type",
    "ChatParticipant": ".chat_participant",
    "ChatParticipantDetails": ".chat_participant_details",
    "ChatParticipantDetailsRole": ".chat_participant_details_role",
    "ChatParticipantDetailsType": ".chat_participant_details_type",
    "ChatParticipantRole": ".chat_participant_role",
    "ChatParticipantType": ".chat_participant_type",
    "ChatRoom": ".chat_room",
    "ChatRoomRequest": ".chat_room_request",
    "ChatRoomRequestOwnerType": ".chat_room_request_owner_type",
    "ChatRoomRequestStatus": ".chat_room_request_status",
    "ChatRoomRequestType": ".chat_room_request_type",
    "ChatRoomUpdateRequest": ".chat_room_update_request",
    "ChatRoomUpdateRequestStatus": ".chat_room_update_request_status",
    "Error": ".error",
    "ErrorError": ".error_error",
    "HealthCheck": ".health_check",
    "HealthCheckServices": ".health_check_services",
    "HealthCheckServicesDatabase": ".health_check_services_database",
    "HealthCheckServicesOban": ".health_check_services_oban",
    "NotFoundErrorBody": ".not_found_error_body",
    "NotFoundErrorBodyError": ".not_found_error_body_error",
    "Task": ".task",
    "TaskRequest": ".task_request",
    "TaskStatus": ".task_status",
    "TestResponse": ".test_response",
    "TestResponseRequestInfo": ".test_response_request_info",
    "Thread": ".thread",
    "Tool": ".tool",
    "ToolCreatedByType": ".tool_created_by_type",
    "ToolRequest": ".tool_request",
    "ToolUpdateRequest": ".tool_update_request",
    "UpdateUserDetails": ".update_user_details",
    "UserDetails": ".user_details",
    "ValidationError": ".validation_error",
    "ValidationErrorError": ".validation_error_error",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Agent",
    "AgentRequest",
    "AgentUpdateRequest",
    "AvailableParticipant",
    "AvailableParticipantType",
    "ChatMessage",
    "ChatMessageRequest",
    "ChatMessageRequestMentionsItem",
    "ChatMessageRequestMessageType",
    "ChatMessageRequestSenderType",
    "ChatParticipant",
    "ChatParticipantDetails",
    "ChatParticipantDetailsRole",
    "ChatParticipantDetailsType",
    "ChatParticipantRole",
    "ChatParticipantType",
    "ChatRoom",
    "ChatRoomRequest",
    "ChatRoomRequestOwnerType",
    "ChatRoomRequestStatus",
    "ChatRoomRequestType",
    "ChatRoomUpdateRequest",
    "ChatRoomUpdateRequestStatus",
    "Error",
    "ErrorError",
    "HealthCheck",
    "HealthCheckServices",
    "HealthCheckServicesDatabase",
    "HealthCheckServicesOban",
    "NotFoundErrorBody",
    "NotFoundErrorBodyError",
    "Task",
    "TaskRequest",
    "TaskStatus",
    "TestResponse",
    "TestResponseRequestInfo",
    "Thread",
    "Tool",
    "ToolCreatedByType",
    "ToolRequest",
    "ToolUpdateRequest",
    "UpdateUserDetails",
    "UserDetails",
    "ValidationError",
    "ValidationErrorError",
]
