# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentUpdateRequest(UniversalBaseModel):
    """
    Request to update an agent (all fields optional for partial updates)
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent Description
    """

    is_external: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If the agent's reasoning loop runs externally
    """

    is_global: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If the agent is globally accessible
    """

    model_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    LLM Model Type
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent Name
    """

    organization_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization ID
    """

    structured_output_schema: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(
        default=None
    )
    """
    Structured Output Schema
    """

    system_prompt_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    System Prompt ID
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
