# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Agent(UniversalBaseModel):
    """
    An AI agent
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent Description
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent ID
    """

    inserted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Created At
    """

    is_external: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If the agent's reasoning loop runs externally
    """

    is_global: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If the agent is globally accessible
    """

    model_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    LLM Model Type (null for external agents)
    """

    name: str = pydantic.Field()
    """
    Agent Name
    """

    organization_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization ID
    """

    owner_uuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    Owner UUID
    """

    structured_output_schema: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(
        default=None
    )
    """
    Structured Output Schema
    """

    system_prompt_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    System Prompt ID (null for external agents)
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Updated At
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
