# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .available_participant_type import AvailableParticipantType


class AvailableParticipant(UniversalBaseModel):
    """
    A user or agent available to be added to a chat room (not yet a participant)
    """

    agent_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent name (for Agent type)
    """

    avatar_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Avatar URL
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    User email (for User type)
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    User first name (for User type)
    """

    id: str = pydantic.Field()
    """
    User UUID or Agent ID
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    User last name (for User type)
    """

    name: str = pydantic.Field()
    """
    Display name
    """

    type: AvailableParticipantType = pydantic.Field()
    """
    Type (User or Agent)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
