# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_room_update_request_status import ChatRoomUpdateRequestStatus


class ChatRoomUpdateRequest(UniversalBaseModel):
    """
    Request to update a chat room (all fields optional for partial updates)
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional metadata
    """

    status: typing.Optional[ChatRoomUpdateRequestStatus] = pydantic.Field(default=None)
    """
    Chat room status
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Chat room title
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
