# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_participant_role import ChatParticipantRole
from .chat_participant_type import ChatParticipantType


class ChatParticipant(UniversalBaseModel):
    """
    A chat room participant (raw format returned by add/remove operations)
    """

    id: str = pydantic.Field()
    """
    Participant ID (User UUID or Agent ID)
    """

    role: ChatParticipantRole = pydantic.Field()
    """
    Participant role
    """

    status: str = pydantic.Field()
    """
    Participant status
    """

    type: ChatParticipantType = pydantic.Field()
    """
    Participant type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
