# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_room_request_owner_type import ChatRoomRequestOwnerType
from .chat_room_request_status import ChatRoomRequestStatus
from .chat_room_request_type import ChatRoomRequestType


class ChatRoomRequest(UniversalBaseModel):
    """
    Request to create a chat room
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional metadata
    """

    owner_id: str = pydantic.Field()
    """
    ID of the owner (User's fusionauth_uuid or Agent's id)
    """

    owner_type: ChatRoomRequestOwnerType = pydantic.Field()
    """
    Type of the owner
    """

    status: ChatRoomRequestStatus = pydantic.Field()
    """
    Chat room status
    """

    task_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Associated task ID
    """

    title: str = pydantic.Field()
    """
    Chat room title
    """

    type: ChatRoomRequestType = pydantic.Field()
    """
    Chat room type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
