# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_message_request_mentions_item import ChatMessageRequestMentionsItem
from .chat_message_request_message_type import ChatMessageRequestMessageType
from .chat_message_request_sender_type import ChatMessageRequestSenderType


class ChatMessageRequest(UniversalBaseModel):
    """
    Request to create a chat message
    """

    content: str = pydantic.Field()
    """
    Message content. To mention users, include their username with @ prefix (e.g. '@Task Owner hello')
    """

    mentions: typing.Optional[typing.List[ChatMessageRequestMentionsItem]] = pydantic.Field(default=None)
    """
    List of mentioned users. Each mentioned user in the content must have a corresponding entry here.
    """

    message_type: typing.Optional[ChatMessageRequestMessageType] = pydantic.Field(default=None)
    """
    Type of message to send
    """

    sender_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the sender. Required only when sender_type is Agent. For User, the authenticated user's ID is used.
    """

    sender_type: typing.Optional[ChatMessageRequestSenderType] = pydantic.Field(default=None)
    """
    Type of sender (User or Agent)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
