# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_participant_details_role import ChatParticipantDetailsRole
from .chat_participant_details_type import ChatParticipantDetailsType


class ChatParticipantDetails(UniversalBaseModel):
    """
    A chat room participant with user/agent details (returned by list endpoint)
    """

    agent_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent name (for Agent participants)
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    User email (for User participants)
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    User first name (for User participants)
    """

    id: str = pydantic.Field()
    """
    User UUID or Agent ID
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    User last name (for User participants)
    """

    role: ChatParticipantDetailsRole = pydantic.Field()
    """
    Participant role
    """

    status: str = pydantic.Field()
    """
    Participant status
    """

    type: ChatParticipantDetailsType = pydantic.Field()
    """
    Participant type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
