# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChatMessage(UniversalBaseModel):
    """
    A chat message
    """

    chat_room_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Chat Room ID
    """

    content: str = pydantic.Field()
    """
    Message content
    """

    id: str = pydantic.Field()
    """
    Message ID
    """

    inserted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Created At
    """

    message_type: str = pydantic.Field()
    """
    Message type
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional metadata
    """

    sender_id: str = pydantic.Field()
    """
    Sender ID
    """

    sender_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of sender (full name for Users, name for Agents)
    """

    sender_type: str = pydantic.Field()
    """
    Sender type (User or Agent)
    """

    thread_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Thread ID
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Updated At
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
