# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChatRoom(UniversalBaseModel):
    """
    A chat room
    """

    deleted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Deleted At
    """

    id: str = pydantic.Field()
    """
    Chat Room ID
    """

    inserted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Created At
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional metadata
    """

    status: str = pydantic.Field()
    """
    Chat Room Status
    """

    task_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Associated Task ID
    """

    title: str = pydantic.Field()
    """
    Chat Room Title
    """

    type: str = pydantic.Field()
    """
    Chat Room Type
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Updated At
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
