# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChatMessageRequestMentionsItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Mentioned user/agent ID
    """

    username: str = pydantic.Field()
    """
    Username as it appears in the content (without @ prefix)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
