# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .health_check_services import HealthCheckServices


class HealthCheck(UniversalBaseModel):
    """
    Health check response
    """

    api_version: str = pydantic.Field()
    """
    API version
    """

    environment: typing.Optional[str] = pydantic.Field(default=None)
    """
    Environment
    """

    features: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Enabled features
    """

    services: typing.Optional[HealthCheckServices] = None
    status: str = pydantic.Field()
    """
    Overall system status
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    Timestamp
    """

    version: str = pydantic.Field()
    """
    Application version
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
