# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .task_status import TaskStatus


class Task(UniversalBaseModel):
    """
    A user task with status tracking and agent assignment
    """

    creator_id: str = pydantic.Field()
    """
    ID of the creator (user or agent) who created this task. This is a polymorphic field that can reference either a user UUID or an agent UUID.
    """

    description: str = pydantic.Field()
    """
    Brief description of the task
    """

    id: str = pydantic.Field()
    """
    Unique task identifier
    """

    inserted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp when the task was created
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional task metadata (custom key-value pairs)
    """

    status: TaskStatus = pydantic.Field()
    """
    Current status of the task
    """

    summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    Longer summary with additional details
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp when the task was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
