# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TaskRequest(UniversalBaseModel):
    """
    Request to create a task
    """

    agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Target agent ID to assign this task to. Required unless an 'Executive Assistant' agent exists in your organization.
    """

    description: str = pydantic.Field()
    """
    Brief description of the task
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional task metadata (key-value pairs for custom fields)
    """

    summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional longer summary with additional details about the task
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
