# This file was auto-generated by Fern from our API Definition.

import typing

TaskStatus = typing.Union[
    typing.Literal["reviewing", "in_progress", "completed", "failed", "engaging", "waiting", "new"], typing.Any
]
