# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .test_response_request_info import TestResponseRequestInfo


class TestResponse(UniversalBaseModel):
    """
    Test endpoint response
    """

    api_version: str = pydantic.Field()
    """
    API version
    """

    auth_type: str = pydantic.Field()
    """
    Authentication method used
    """

    message: str = pydantic.Field()
    """
    Success message
    """

    permissions: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Available permissions
    """

    request_info: typing.Optional[TestResponseRequestInfo] = None
    status: str = pydantic.Field()
    """
    Response status
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
