# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Thread(UniversalBaseModel):
    """
    A message thread
    """

    chat_room_id: str = pydantic.Field()
    """
    Chat Room ID
    """

    id: str = pydantic.Field()
    """
    Thread ID
    """

    inserted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Created At
    """

    last_message_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Last Message Time
    """

    message_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of messages in thread
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional metadata
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Thread name
    """

    root_message_id: str = pydantic.Field()
    """
    Root Message ID
    """

    status: str = pydantic.Field()
    """
    Thread status
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Updated At
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
