# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tool_created_by_type import ToolCreatedByType


class Tool(UniversalBaseModel):
    """
    An AI tool
    """

    connection_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Connection configuration
    """

    created_by_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the creator (user UUID or agent ID)
    """

    created_by_type: typing.Optional[ToolCreatedByType] = pydantic.Field(default=None)
    """
    Type of the creator
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tool Description
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tool ID
    """

    inserted_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Created At
    """

    is_global: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If the tool is globally accessible
    """

    json_schema: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    JSON Schema for tool parameters
    """

    name: str = pydantic.Field()
    """
    Tool Name
    """

    organization_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization ID
    """

    owner_uuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    Owner UUID
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Updated At
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
