# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateUserDetails(UniversalBaseModel):
    """
    Request to update user profile details
    """

    bio: typing.Optional[str] = pydantic.Field(default=None)
    """
    User bio
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    First name
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last name
    """

    locale: typing.Optional[str] = pydantic.Field(default=None)
    """
    User locale
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional user metadata
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone number
    """

    timezone: typing.Optional[str] = pydantic.Field(default=None)
    """
    User timezone
    """

    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    Username
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
