# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ValidationErrorError(UniversalBaseModel):
    code: str = pydantic.Field()
    """
    Machine-readable error code
    """

    details: typing.Dict[str, typing.List[str]] = pydantic.Field()
    """
    Field-specific validation errors with JSON Pointer paths (RFC 6901) as keys
    """

    message: str = pydantic.Field()
    """
    Human-readable error message
    """

    request_id: str = pydantic.Field()
    """
    Unique request identifier for tracing and debugging
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
