# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.task import Task
from .list_my_tasks_response_metadata import ListMyTasksResponseMetadata


class ListMyTasksResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[Task]] = None
    metadata: typing.Optional[ListMyTasksResponseMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
