# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .environment import RestClientEnvironment

if typing.TYPE_CHECKING:
    from .agents.client import AgentsClient, AsyncAgentsClient
    from .chat_messages.client import AsyncChatMessagesClient, ChatMessagesClient
    from .chat_participants.client import AsyncChatParticipantsClient, ChatParticipantsClient
    from .chat_rooms.client import AsyncChatRoomsClient, ChatRoomsClient
    from .my_chat_messages.client import AsyncMyChatMessagesClient, MyChatMessagesClient
    from .my_chat_threads.client import AsyncMyChatThreadsClient, MyChatThreadsClient
    from .my_chats.client import AsyncMyChatsClient, MyChatsClient
    from .my_profile.client import AsyncMyProfileClient, MyProfileClient
    from .my_tasks.client import AsyncMyTasksClient, MyTasksClient
    from .system.client import AsyncSystemClient, SystemClient
    from .test.client import AsyncTestClient, TestClient
    from .tools.client import AsyncToolsClient, ToolsClient


class RestClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : RestClientEnvironment
        The environment to use for requests from the client. from .environment import RestClientEnvironment



        Defaults to RestClientEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from thenvoi_client_rest import RestClient

    client = RestClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: RestClientEnvironment = RestClientEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._agents: typing.Optional[AgentsClient] = None
        self._chat_rooms: typing.Optional[ChatRoomsClient] = None
        self._chat_participants: typing.Optional[ChatParticipantsClient] = None
        self._chat_messages: typing.Optional[ChatMessagesClient] = None
        self._system: typing.Optional[SystemClient] = None
        self._my_chats: typing.Optional[MyChatsClient] = None
        self._my_chat_messages: typing.Optional[MyChatMessagesClient] = None
        self._my_chat_threads: typing.Optional[MyChatThreadsClient] = None
        self._my_profile: typing.Optional[MyProfileClient] = None
        self._my_tasks: typing.Optional[MyTasksClient] = None
        self._test: typing.Optional[TestClient] = None
        self._tools: typing.Optional[ToolsClient] = None

    @property
    def agents(self):
        if self._agents is None:
            from .agents.client import AgentsClient  # noqa: E402

            self._agents = AgentsClient(client_wrapper=self._client_wrapper)
        return self._agents

    @property
    def chat_rooms(self):
        if self._chat_rooms is None:
            from .chat_rooms.client import ChatRoomsClient  # noqa: E402

            self._chat_rooms = ChatRoomsClient(client_wrapper=self._client_wrapper)
        return self._chat_rooms

    @property
    def chat_participants(self):
        if self._chat_participants is None:
            from .chat_participants.client import ChatParticipantsClient  # noqa: E402

            self._chat_participants = ChatParticipantsClient(client_wrapper=self._client_wrapper)
        return self._chat_participants

    @property
    def chat_messages(self):
        if self._chat_messages is None:
            from .chat_messages.client import ChatMessagesClient  # noqa: E402

            self._chat_messages = ChatMessagesClient(client_wrapper=self._client_wrapper)
        return self._chat_messages

    @property
    def system(self):
        if self._system is None:
            from .system.client import SystemClient  # noqa: E402

            self._system = SystemClient(client_wrapper=self._client_wrapper)
        return self._system

    @property
    def my_chats(self):
        if self._my_chats is None:
            from .my_chats.client import MyChatsClient  # noqa: E402

            self._my_chats = MyChatsClient(client_wrapper=self._client_wrapper)
        return self._my_chats

    @property
    def my_chat_messages(self):
        if self._my_chat_messages is None:
            from .my_chat_messages.client import MyChatMessagesClient  # noqa: E402

            self._my_chat_messages = MyChatMessagesClient(client_wrapper=self._client_wrapper)
        return self._my_chat_messages

    @property
    def my_chat_threads(self):
        if self._my_chat_threads is None:
            from .my_chat_threads.client import MyChatThreadsClient  # noqa: E402

            self._my_chat_threads = MyChatThreadsClient(client_wrapper=self._client_wrapper)
        return self._my_chat_threads

    @property
    def my_profile(self):
        if self._my_profile is None:
            from .my_profile.client import MyProfileClient  # noqa: E402

            self._my_profile = MyProfileClient(client_wrapper=self._client_wrapper)
        return self._my_profile

    @property
    def my_tasks(self):
        if self._my_tasks is None:
            from .my_tasks.client import MyTasksClient  # noqa: E402

            self._my_tasks = MyTasksClient(client_wrapper=self._client_wrapper)
        return self._my_tasks

    @property
    def test(self):
        if self._test is None:
            from .test.client import TestClient  # noqa: E402

            self._test = TestClient(client_wrapper=self._client_wrapper)
        return self._test

    @property
    def tools(self):
        if self._tools is None:
            from .tools.client import ToolsClient  # noqa: E402

            self._tools = ToolsClient(client_wrapper=self._client_wrapper)
        return self._tools


class AsyncRestClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : RestClientEnvironment
        The environment to use for requests from the client. from .environment import RestClientEnvironment



        Defaults to RestClientEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from thenvoi_client_rest import AsyncRestClient

    client = AsyncRestClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: RestClientEnvironment = RestClientEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._agents: typing.Optional[AsyncAgentsClient] = None
        self._chat_rooms: typing.Optional[AsyncChatRoomsClient] = None
        self._chat_participants: typing.Optional[AsyncChatParticipantsClient] = None
        self._chat_messages: typing.Optional[AsyncChatMessagesClient] = None
        self._system: typing.Optional[AsyncSystemClient] = None
        self._my_chats: typing.Optional[AsyncMyChatsClient] = None
        self._my_chat_messages: typing.Optional[AsyncMyChatMessagesClient] = None
        self._my_chat_threads: typing.Optional[AsyncMyChatThreadsClient] = None
        self._my_profile: typing.Optional[AsyncMyProfileClient] = None
        self._my_tasks: typing.Optional[AsyncMyTasksClient] = None
        self._test: typing.Optional[AsyncTestClient] = None
        self._tools: typing.Optional[AsyncToolsClient] = None

    @property
    def agents(self):
        if self._agents is None:
            from .agents.client import AsyncAgentsClient  # noqa: E402

            self._agents = AsyncAgentsClient(client_wrapper=self._client_wrapper)
        return self._agents

    @property
    def chat_rooms(self):
        if self._chat_rooms is None:
            from .chat_rooms.client import AsyncChatRoomsClient  # noqa: E402

            self._chat_rooms = AsyncChatRoomsClient(client_wrapper=self._client_wrapper)
        return self._chat_rooms

    @property
    def chat_participants(self):
        if self._chat_participants is None:
            from .chat_participants.client import AsyncChatParticipantsClient  # noqa: E402

            self._chat_participants = AsyncChatParticipantsClient(client_wrapper=self._client_wrapper)
        return self._chat_participants

    @property
    def chat_messages(self):
        if self._chat_messages is None:
            from .chat_messages.client import AsyncChatMessagesClient  # noqa: E402

            self._chat_messages = AsyncChatMessagesClient(client_wrapper=self._client_wrapper)
        return self._chat_messages

    @property
    def system(self):
        if self._system is None:
            from .system.client import AsyncSystemClient  # noqa: E402

            self._system = AsyncSystemClient(client_wrapper=self._client_wrapper)
        return self._system

    @property
    def my_chats(self):
        if self._my_chats is None:
            from .my_chats.client import AsyncMyChatsClient  # noqa: E402

            self._my_chats = AsyncMyChatsClient(client_wrapper=self._client_wrapper)
        return self._my_chats

    @property
    def my_chat_messages(self):
        if self._my_chat_messages is None:
            from .my_chat_messages.client import AsyncMyChatMessagesClient  # noqa: E402

            self._my_chat_messages = AsyncMyChatMessagesClient(client_wrapper=self._client_wrapper)
        return self._my_chat_messages

    @property
    def my_chat_threads(self):
        if self._my_chat_threads is None:
            from .my_chat_threads.client import AsyncMyChatThreadsClient  # noqa: E402

            self._my_chat_threads = AsyncMyChatThreadsClient(client_wrapper=self._client_wrapper)
        return self._my_chat_threads

    @property
    def my_profile(self):
        if self._my_profile is None:
            from .my_profile.client import AsyncMyProfileClient  # noqa: E402

            self._my_profile = AsyncMyProfileClient(client_wrapper=self._client_wrapper)
        return self._my_profile

    @property
    def my_tasks(self):
        if self._my_tasks is None:
            from .my_tasks.client import AsyncMyTasksClient  # noqa: E402

            self._my_tasks = AsyncMyTasksClient(client_wrapper=self._client_wrapper)
        return self._my_tasks

    @property
    def test(self):
        if self._test is None:
            from .test.client import AsyncTestClient  # noqa: E402

            self._test = AsyncTestClient(client_wrapper=self._client_wrapper)
        return self._test

    @property
    def tools(self):
        if self._tools is None:
            from .tools.client import AsyncToolsClient  # noqa: E402

            self._tools = AsyncToolsClient(client_wrapper=self._client_wrapper)
        return self._tools


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: RestClientEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
