# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.task import Task
from ..types.task_request import TaskRequest
from .raw_client import AsyncRawMyTasksClient, RawMyTasksClient
from .types.list_my_tasks_request_status import ListMyTasksRequestStatus
from .types.list_my_tasks_response import ListMyTasksResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MyTasksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMyTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMyTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMyTasksClient
        """
        return self._raw_client

    def list_my_tasks(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        status: typing.Optional[ListMyTasksRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyTasksResponse:
        """
        Returns a paginated list of all tasks owned by the authenticated user.

        Tasks can be filtered by status and paginated for efficient retrieval.
        Each task includes its current status, assigned agent (if any), and custom metadata.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        status : typing.Optional[ListMyTasksRequestStatus]
            Filter by status

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyTasksResponse
            Tasks

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_tasks.list_my_tasks(
            page=1,
            per_page=1,
            status="reviewing",
        )
        """
        _response = self._raw_client.list_my_tasks(
            page=page, per_page=per_page, status=status, request_options=request_options
        )
        return _response.data

    def create_my_task(self, *, task: TaskRequest, request_options: typing.Optional[RequestOptions] = None) -> Task:
        """
        Creates a new task owned by the authenticated user.

        The task will be assigned to the specified agent. If no agent_id is provided,
        the task will be assigned to the 'Executive Assistant' agent (if one exists in your organization).

        All tasks start with a status of 'new' and can include custom metadata for additional context.

        Parameters
        ----------
        task : TaskRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            Task Created

        Examples
        --------
        from thenvoi_client_rest import RestClient, TaskRequest

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_tasks.create_my_task(
            task=TaskRequest(
                agent_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                description="Review Q4 financial reports",
                metadata={
                    "category": "finance",
                    "deadline": "2025-12-31",
                    "priority": "high",
                },
                summary="Review the Q4 financial reports and prepare a summary of key findings for the board meeting",
            ),
        )
        """
        _response = self._raw_client.create_my_task(task=task, request_options=request_options)
        return _response.data

    def get_my_task(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Task:
        """
        Retrieves a specific task by ID.

        You can only access tasks that you own. Attempting to access another user's task
        will return a 404 error (security-first: doesn't leak task existence).

        Parameters
        ----------
        id : str
            Task ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            Task

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_tasks.get_my_task(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.get_my_task(id, request_options=request_options)
        return _response.data

    def delete_my_task(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        Permanently deletes a task by ID.

        You can only delete tasks that you own. Attempting to delete another user's task
        will return a 404 error (security-first: doesn't leak task existence).

        Note: This operation cannot be undone.

        Parameters
        ----------
        id : str
            Task ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            No Content

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_tasks.delete_my_task(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.delete_my_task(id, request_options=request_options)
        return _response.data


class AsyncMyTasksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMyTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMyTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMyTasksClient
        """
        return self._raw_client

    async def list_my_tasks(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        status: typing.Optional[ListMyTasksRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyTasksResponse:
        """
        Returns a paginated list of all tasks owned by the authenticated user.

        Tasks can be filtered by status and paginated for efficient retrieval.
        Each task includes its current status, assigned agent (if any), and custom metadata.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        status : typing.Optional[ListMyTasksRequestStatus]
            Filter by status

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyTasksResponse
            Tasks

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_tasks.list_my_tasks(
                page=1,
                per_page=1,
                status="reviewing",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_tasks(
            page=page, per_page=per_page, status=status, request_options=request_options
        )
        return _response.data

    async def create_my_task(
        self, *, task: TaskRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Task:
        """
        Creates a new task owned by the authenticated user.

        The task will be assigned to the specified agent. If no agent_id is provided,
        the task will be assigned to the 'Executive Assistant' agent (if one exists in your organization).

        All tasks start with a status of 'new' and can include custom metadata for additional context.

        Parameters
        ----------
        task : TaskRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            Task Created

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient, TaskRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_tasks.create_my_task(
                task=TaskRequest(
                    agent_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                    description="Review Q4 financial reports",
                    metadata={
                        "category": "finance",
                        "deadline": "2025-12-31",
                        "priority": "high",
                    },
                    summary="Review the Q4 financial reports and prepare a summary of key findings for the board meeting",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_my_task(task=task, request_options=request_options)
        return _response.data

    async def get_my_task(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Task:
        """
        Retrieves a specific task by ID.

        You can only access tasks that you own. Attempting to access another user's task
        will return a 404 error (security-first: doesn't leak task existence).

        Parameters
        ----------
        id : str
            Task ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            Task

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_tasks.get_my_task(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_my_task(id, request_options=request_options)
        return _response.data

    async def delete_my_task(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Optional[typing.Any]]:
        """
        Permanently deletes a task by ID.

        You can only delete tasks that you own. Attempting to delete another user's task
        will return a 404 error (security-first: doesn't leak task existence).

        Note: This operation cannot be undone.

        Parameters
        ----------
        id : str
            Task ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Optional[typing.Any]]
            No Content

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_tasks.delete_my_task(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_my_task(id, request_options=request_options)
        return _response.data
