# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawMyChatThreadsClient, RawMyChatThreadsClient
from .types.get_my_chat_thread_response import GetMyChatThreadResponse
from .types.list_my_chat_threads_response import ListMyChatThreadsResponse


class MyChatThreadsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMyChatThreadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMyChatThreadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMyChatThreadsClient
        """
        return self._raw_client

    def list_my_chat_threads(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyChatThreadsResponse:
        """
        Returns a list of message threads in a chat room you're participating in

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyChatThreadsResponse
            Chat Threads

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_chat_threads.list_my_chat_threads(
            chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            page=1,
            per_page=1,
        )
        """
        _response = self._raw_client.list_my_chat_threads(
            chat_id, page=page, per_page=per_page, request_options=request_options
        )
        return _response.data

    def get_my_chat_thread(
        self,
        chat_id: str,
        thread_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetMyChatThreadResponse:
        """
        Returns messages in a specific thread

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        thread_id : str
            Thread ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMyChatThreadResponse
            Thread Messages

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_chat_threads.get_my_chat_thread(
            chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            thread_id="b45689eb-48df-4e6c-8379-710f36e6f196",
            page=1,
            per_page=1,
        )
        """
        _response = self._raw_client.get_my_chat_thread(
            chat_id, thread_id, page=page, per_page=per_page, request_options=request_options
        )
        return _response.data


class AsyncMyChatThreadsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMyChatThreadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMyChatThreadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMyChatThreadsClient
        """
        return self._raw_client

    async def list_my_chat_threads(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyChatThreadsResponse:
        """
        Returns a list of message threads in a chat room you're participating in

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyChatThreadsResponse
            Chat Threads

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_chat_threads.list_my_chat_threads(
                chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                page=1,
                per_page=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_chat_threads(
            chat_id, page=page, per_page=per_page, request_options=request_options
        )
        return _response.data

    async def get_my_chat_thread(
        self,
        chat_id: str,
        thread_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetMyChatThreadResponse:
        """
        Returns messages in a specific thread

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        thread_id : str
            Thread ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMyChatThreadResponse
            Thread Messages

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_chat_threads.get_my_chat_thread(
                chat_id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                thread_id="b45689eb-48df-4e6c-8379-710f36e6f196",
                page=1,
                per_page=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_my_chat_thread(
            chat_id, thread_id, page=page, per_page=per_page, request_options=request_options
        )
        return _response.data
