# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetVersionResponse(UniversalBaseModel):
    built_at: str = pydantic.Field()
    """
    Build timestamp
    """

    commit: str = pydantic.Field()
    """
    Git commit hash
    """

    version: str = pydantic.Field()
    """
    API semantic version
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
