# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_chat_response import CreateChatResponse
    from .get_chat_response import GetChatResponse
    from .list_chats_request_status import ListChatsRequestStatus
    from .list_chats_request_type import ListChatsRequestType
    from .list_chats_response import ListChatsResponse
    from .list_chats_response_metadata import ListChatsResponseMetadata
    from .update_chat_response import UpdateChatResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateChatResponse": ".create_chat_response",
    "GetChatResponse": ".get_chat_response",
    "ListChatsRequestStatus": ".list_chats_request_status",
    "ListChatsRequestType": ".list_chats_request_type",
    "ListChatsResponse": ".list_chats_response",
    "ListChatsResponseMetadata": ".list_chats_response_metadata",
    "UpdateChatResponse": ".update_chat_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateChatResponse",
    "GetChatResponse",
    "ListChatsRequestStatus",
    "ListChatsRequestType",
    "ListChatsResponse",
    "ListChatsResponseMetadata",
    "UpdateChatResponse",
]
