# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chat_message_request import ChatMessageRequest
from .raw_client import AsyncRawChatMessagesClient, RawChatMessagesClient
from .types.create_chat_message_response import CreateChatMessageResponse
from .types.delete_chat_message_response import DeleteChatMessageResponse
from .types.list_chat_messages_request_message_type import ListChatMessagesRequestMessageType
from .types.list_chat_messages_response import ListChatMessagesResponse
from .types.mark_message_failed_response import MarkMessageFailedResponse
from .types.mark_message_processed_response import MarkMessageProcessedResponse
from .types.mark_message_processing_response import MarkMessageProcessingResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChatMessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChatMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChatMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChatMessagesClient
        """
        return self._raw_client

    def list_chat_messages(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        since: typing.Optional[dt.datetime] = None,
        message_type: typing.Optional[ListChatMessagesRequestMessageType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChatMessagesResponse:
        """
        Returns a list of messages in a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        since : typing.Optional[dt.datetime]
            Messages after timestamp

        message_type : typing.Optional[ListChatMessagesRequestMessageType]
            Filter by message type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChatMessagesResponse
            Chat Messages

        Examples
        --------
        import datetime

        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_messages.list_chat_messages(
            chat_id="chat_id",
            page=1,
            per_page=1,
            since=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            message_type="text",
        )
        """
        _response = self._raw_client.list_chat_messages(
            chat_id,
            page=page,
            per_page=per_page,
            since=since,
            message_type=message_type,
            request_options=request_options,
        )
        return _response.data

    def create_chat_message(
        self, chat_id: str, *, message: ChatMessageRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateChatMessageResponse:
        """
        Creates a new message in a chat room.

        To mention users in the message:
        1. Include the username with @ prefix in the content (e.g. "@Task Owner hello")
        2. Add the corresponding user details in the mentions array

        Example:
        ```json
        {
          "message": {
            "content": "@Task Owner hello",
            "message_type": "text",
            "sender_type": "User",
            "mentions": [
              {
                "id": "8d6257a4-6a20-4df3-8f19-e69a8138f519",
                "username": "Task Owner"
              }
            ]
          }
        }
        ```

        When sending a message as an agent:
        1. Set sender_type to "Agent"
        2. Provide the agent ID in sender_id
        3. Ensure the agent belongs to the authenticated user and is a chat participant

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        message : ChatMessageRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateChatMessageResponse
            Created Message

        Examples
        --------
        from thenvoi_client_rest import ChatMessageRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_messages.create_chat_message(
            chat_id="chat_id",
            message=ChatMessageRequest(
                content="content",
            ),
        )
        """
        _response = self._raw_client.create_chat_message(chat_id, message=message, request_options=request_options)
        return _response.data

    def delete_chat_message(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteChatMessageResponse:
        """
        Deletes a message from a chat room. Only the sender or chat room owner can delete messages.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteChatMessageResponse
            No Content

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_messages.delete_chat_message(
            chat_id="chat_id",
            id="id",
        )
        """
        _response = self._raw_client.delete_chat_message(chat_id, id, request_options=request_options)
        return _response.data

    def mark_message_failed(
        self, chat_id: str, id: str, *, error: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MarkMessageFailedResponse:
        """
        Marks a message processing as failed by a participant. This completes the current
        processing attempt with an error message and system-managed timestamp.

        This endpoint automatically:
        - Sets the current attempt's completed_at timestamp (system-managed)
        - Sets the current attempt status to "failed"
        - Records the error message in the current attempt
        - Updates the participant's delivery status to "failed"

        Note: This endpoint requires an active processing attempt. If no processing attempt exists,
        it will return a 422 error.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        error : str
            Error message describing why processing failed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarkMessageFailedResponse
            Message marked as failed

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_messages.mark_message_failed(
            chat_id="chat_id",
            id="id",
            error="error",
        )
        """
        _response = self._raw_client.mark_message_failed(chat_id, id, error=error, request_options=request_options)
        return _response.data

    def mark_message_processed(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MarkMessageProcessedResponse:
        """
        Marks a message as successfully processed by a participant. This completes the current
        processing attempt with a system-managed timestamp.

        This endpoint automatically:
        - Sets the current attempt's completed_at timestamp (system-managed)
        - Sets the current attempt status to "success"
        - Sets the participant's processed_at timestamp (system-managed)
        - Updates the participant's delivery status to "processed"

        Note: This endpoint requires an active processing attempt. If no processing attempt exists,
        it will return a 422 error.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarkMessageProcessedResponse
            Message marked as processed

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_messages.mark_message_processed(
            chat_id="chat_id",
            id="id",
        )
        """
        _response = self._raw_client.mark_message_processed(chat_id, id, request_options=request_options)
        return _response.data

    def mark_message_processing(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MarkMessageProcessingResponse:
        """
        Marks a message as being processed by a participant. This creates a new processing attempt
        with a system-managed timestamp. The participant must be a member of the chat room.

        This endpoint automatically:
        - Creates a new attempt with auto-incremented attempt_number
        - Sets the attempt status to "processing"
        - Records the started_at timestamp (system-managed)
        - Updates the participant's delivery status to "processing"

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarkMessageProcessingResponse
            Message marked as processing

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.chat_messages.mark_message_processing(
            chat_id="chat_id",
            id="id",
        )
        """
        _response = self._raw_client.mark_message_processing(chat_id, id, request_options=request_options)
        return _response.data


class AsyncChatMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChatMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChatMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChatMessagesClient
        """
        return self._raw_client

    async def list_chat_messages(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        since: typing.Optional[dt.datetime] = None,
        message_type: typing.Optional[ListChatMessagesRequestMessageType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChatMessagesResponse:
        """
        Returns a list of messages in a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        since : typing.Optional[dt.datetime]
            Messages after timestamp

        message_type : typing.Optional[ListChatMessagesRequestMessageType]
            Filter by message type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChatMessagesResponse
            Chat Messages

        Examples
        --------
        import asyncio
        import datetime

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_messages.list_chat_messages(
                chat_id="chat_id",
                page=1,
                per_page=1,
                since=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                message_type="text",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_chat_messages(
            chat_id,
            page=page,
            per_page=per_page,
            since=since,
            message_type=message_type,
            request_options=request_options,
        )
        return _response.data

    async def create_chat_message(
        self, chat_id: str, *, message: ChatMessageRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateChatMessageResponse:
        """
        Creates a new message in a chat room.

        To mention users in the message:
        1. Include the username with @ prefix in the content (e.g. "@Task Owner hello")
        2. Add the corresponding user details in the mentions array

        Example:
        ```json
        {
          "message": {
            "content": "@Task Owner hello",
            "message_type": "text",
            "sender_type": "User",
            "mentions": [
              {
                "id": "8d6257a4-6a20-4df3-8f19-e69a8138f519",
                "username": "Task Owner"
              }
            ]
          }
        }
        ```

        When sending a message as an agent:
        1. Set sender_type to "Agent"
        2. Provide the agent ID in sender_id
        3. Ensure the agent belongs to the authenticated user and is a chat participant

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        message : ChatMessageRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateChatMessageResponse
            Created Message

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient, ChatMessageRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_messages.create_chat_message(
                chat_id="chat_id",
                message=ChatMessageRequest(
                    content="content",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_chat_message(
            chat_id, message=message, request_options=request_options
        )
        return _response.data

    async def delete_chat_message(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteChatMessageResponse:
        """
        Deletes a message from a chat room. Only the sender or chat room owner can delete messages.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteChatMessageResponse
            No Content

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_messages.delete_chat_message(
                chat_id="chat_id",
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_chat_message(chat_id, id, request_options=request_options)
        return _response.data

    async def mark_message_failed(
        self, chat_id: str, id: str, *, error: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MarkMessageFailedResponse:
        """
        Marks a message processing as failed by a participant. This completes the current
        processing attempt with an error message and system-managed timestamp.

        This endpoint automatically:
        - Sets the current attempt's completed_at timestamp (system-managed)
        - Sets the current attempt status to "failed"
        - Records the error message in the current attempt
        - Updates the participant's delivery status to "failed"

        Note: This endpoint requires an active processing attempt. If no processing attempt exists,
        it will return a 422 error.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        error : str
            Error message describing why processing failed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarkMessageFailedResponse
            Message marked as failed

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_messages.mark_message_failed(
                chat_id="chat_id",
                id="id",
                error="error",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.mark_message_failed(
            chat_id, id, error=error, request_options=request_options
        )
        return _response.data

    async def mark_message_processed(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MarkMessageProcessedResponse:
        """
        Marks a message as successfully processed by a participant. This completes the current
        processing attempt with a system-managed timestamp.

        This endpoint automatically:
        - Sets the current attempt's completed_at timestamp (system-managed)
        - Sets the current attempt status to "success"
        - Sets the participant's processed_at timestamp (system-managed)
        - Updates the participant's delivery status to "processed"

        Note: This endpoint requires an active processing attempt. If no processing attempt exists,
        it will return a 422 error.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarkMessageProcessedResponse
            Message marked as processed

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_messages.mark_message_processed(
                chat_id="chat_id",
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.mark_message_processed(chat_id, id, request_options=request_options)
        return _response.data

    async def mark_message_processing(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MarkMessageProcessingResponse:
        """
        Marks a message as being processed by a participant. This creates a new processing attempt
        with a system-managed timestamp. The participant must be a member of the chat room.

        This endpoint automatically:
        - Creates a new attempt with auto-incremented attempt_number
        - Sets the attempt status to "processing"
        - Records the started_at timestamp (system-managed)
        - Updates the participant's delivery status to "processing"

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarkMessageProcessingResponse
            Message marked as processing

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat_messages.mark_message_processing(
                chat_id="chat_id",
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.mark_message_processing(chat_id, id, request_options=request_options)
        return _response.data
