# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.chat_message_request import ChatMessageRequest
from ..types.error import Error
from ..types.validation_error import ValidationError
from .types.create_chat_message_response import CreateChatMessageResponse
from .types.delete_chat_message_response import DeleteChatMessageResponse
from .types.list_chat_messages_request_message_type import ListChatMessagesRequestMessageType
from .types.list_chat_messages_response import ListChatMessagesResponse
from .types.mark_message_failed_response import MarkMessageFailedResponse
from .types.mark_message_processed_response import MarkMessageProcessedResponse
from .types.mark_message_processing_response import MarkMessageProcessingResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawChatMessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_chat_messages(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        since: typing.Optional[dt.datetime] = None,
        message_type: typing.Optional[ListChatMessagesRequestMessageType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListChatMessagesResponse]:
        """
        Returns a list of messages in a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        since : typing.Optional[dt.datetime]
            Messages after timestamp

        message_type : typing.Optional[ListChatMessagesRequestMessageType]
            Filter by message type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListChatMessagesResponse]
            Chat Messages
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages",
            method="GET",
            params={
                "page": page,
                "per_page": per_page,
                "since": serialize_datetime(since) if since is not None else None,
                "message_type": message_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListChatMessagesResponse,
                    parse_obj_as(
                        type_=ListChatMessagesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_chat_message(
        self, chat_id: str, *, message: ChatMessageRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CreateChatMessageResponse]:
        """
        Creates a new message in a chat room.

        To mention users in the message:
        1. Include the username with @ prefix in the content (e.g. "@Task Owner hello")
        2. Add the corresponding user details in the mentions array

        Example:
        ```json
        {
          "message": {
            "content": "@Task Owner hello",
            "message_type": "text",
            "sender_type": "User",
            "mentions": [
              {
                "id": "8d6257a4-6a20-4df3-8f19-e69a8138f519",
                "username": "Task Owner"
              }
            ]
          }
        }
        ```

        When sending a message as an agent:
        1. Set sender_type to "Agent"
        2. Provide the agent ID in sender_id
        3. Ensure the agent belongs to the authenticated user and is a chat participant

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        message : ChatMessageRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateChatMessageResponse]
            Created Message
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages",
            method="POST",
            json={
                "message": convert_and_respect_annotation_metadata(
                    object_=message, annotation=ChatMessageRequest, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateChatMessageResponse,
                    parse_obj_as(
                        type_=CreateChatMessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_chat_message(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeleteChatMessageResponse]:
        """
        Deletes a message from a chat room. Only the sender or chat room owner can delete messages.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeleteChatMessageResponse]
            No Content
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteChatMessageResponse,
                    parse_obj_as(
                        type_=DeleteChatMessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mark_message_failed(
        self, chat_id: str, id: str, *, error: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MarkMessageFailedResponse]:
        """
        Marks a message processing as failed by a participant. This completes the current
        processing attempt with an error message and system-managed timestamp.

        This endpoint automatically:
        - Sets the current attempt's completed_at timestamp (system-managed)
        - Sets the current attempt status to "failed"
        - Records the error message in the current attempt
        - Updates the participant's delivery status to "failed"

        Note: This endpoint requires an active processing attempt. If no processing attempt exists,
        it will return a 422 error.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        error : str
            Error message describing why processing failed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MarkMessageFailedResponse]
            Message marked as failed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages/{jsonable_encoder(id)}/failed",
            method="POST",
            json={
                "error": error,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MarkMessageFailedResponse,
                    parse_obj_as(
                        type_=MarkMessageFailedResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mark_message_processed(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MarkMessageProcessedResponse]:
        """
        Marks a message as successfully processed by a participant. This completes the current
        processing attempt with a system-managed timestamp.

        This endpoint automatically:
        - Sets the current attempt's completed_at timestamp (system-managed)
        - Sets the current attempt status to "success"
        - Sets the participant's processed_at timestamp (system-managed)
        - Updates the participant's delivery status to "processed"

        Note: This endpoint requires an active processing attempt. If no processing attempt exists,
        it will return a 422 error.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MarkMessageProcessedResponse]
            Message marked as processed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages/{jsonable_encoder(id)}/processed",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MarkMessageProcessedResponse,
                    parse_obj_as(
                        type_=MarkMessageProcessedResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mark_message_processing(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MarkMessageProcessingResponse]:
        """
        Marks a message as being processed by a participant. This creates a new processing attempt
        with a system-managed timestamp. The participant must be a member of the chat room.

        This endpoint automatically:
        - Creates a new attempt with auto-incremented attempt_number
        - Sets the attempt status to "processing"
        - Records the started_at timestamp (system-managed)
        - Updates the participant's delivery status to "processing"

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MarkMessageProcessingResponse]
            Message marked as processing
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages/{jsonable_encoder(id)}/processing",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MarkMessageProcessingResponse,
                    parse_obj_as(
                        type_=MarkMessageProcessingResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawChatMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_chat_messages(
        self,
        chat_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        since: typing.Optional[dt.datetime] = None,
        message_type: typing.Optional[ListChatMessagesRequestMessageType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListChatMessagesResponse]:
        """
        Returns a list of messages in a chat room

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        page : typing.Optional[int]
            Page number

        per_page : typing.Optional[int]
            Items per page

        since : typing.Optional[dt.datetime]
            Messages after timestamp

        message_type : typing.Optional[ListChatMessagesRequestMessageType]
            Filter by message type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListChatMessagesResponse]
            Chat Messages
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages",
            method="GET",
            params={
                "page": page,
                "per_page": per_page,
                "since": serialize_datetime(since) if since is not None else None,
                "message_type": message_type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListChatMessagesResponse,
                    parse_obj_as(
                        type_=ListChatMessagesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_chat_message(
        self, chat_id: str, *, message: ChatMessageRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CreateChatMessageResponse]:
        """
        Creates a new message in a chat room.

        To mention users in the message:
        1. Include the username with @ prefix in the content (e.g. "@Task Owner hello")
        2. Add the corresponding user details in the mentions array

        Example:
        ```json
        {
          "message": {
            "content": "@Task Owner hello",
            "message_type": "text",
            "sender_type": "User",
            "mentions": [
              {
                "id": "8d6257a4-6a20-4df3-8f19-e69a8138f519",
                "username": "Task Owner"
              }
            ]
          }
        }
        ```

        When sending a message as an agent:
        1. Set sender_type to "Agent"
        2. Provide the agent ID in sender_id
        3. Ensure the agent belongs to the authenticated user and is a chat participant

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        message : ChatMessageRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateChatMessageResponse]
            Created Message
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages",
            method="POST",
            json={
                "message": convert_and_respect_annotation_metadata(
                    object_=message, annotation=ChatMessageRequest, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateChatMessageResponse,
                    parse_obj_as(
                        type_=CreateChatMessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_chat_message(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeleteChatMessageResponse]:
        """
        Deletes a message from a chat room. Only the sender or chat room owner can delete messages.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeleteChatMessageResponse]
            No Content
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteChatMessageResponse,
                    parse_obj_as(
                        type_=DeleteChatMessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mark_message_failed(
        self, chat_id: str, id: str, *, error: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MarkMessageFailedResponse]:
        """
        Marks a message processing as failed by a participant. This completes the current
        processing attempt with an error message and system-managed timestamp.

        This endpoint automatically:
        - Sets the current attempt's completed_at timestamp (system-managed)
        - Sets the current attempt status to "failed"
        - Records the error message in the current attempt
        - Updates the participant's delivery status to "failed"

        Note: This endpoint requires an active processing attempt. If no processing attempt exists,
        it will return a 422 error.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        error : str
            Error message describing why processing failed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MarkMessageFailedResponse]
            Message marked as failed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages/{jsonable_encoder(id)}/failed",
            method="POST",
            json={
                "error": error,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MarkMessageFailedResponse,
                    parse_obj_as(
                        type_=MarkMessageFailedResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mark_message_processed(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MarkMessageProcessedResponse]:
        """
        Marks a message as successfully processed by a participant. This completes the current
        processing attempt with a system-managed timestamp.

        This endpoint automatically:
        - Sets the current attempt's completed_at timestamp (system-managed)
        - Sets the current attempt status to "success"
        - Sets the participant's processed_at timestamp (system-managed)
        - Updates the participant's delivery status to "processed"

        Note: This endpoint requires an active processing attempt. If no processing attempt exists,
        it will return a 422 error.

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MarkMessageProcessedResponse]
            Message marked as processed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages/{jsonable_encoder(id)}/processed",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MarkMessageProcessedResponse,
                    parse_obj_as(
                        type_=MarkMessageProcessedResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mark_message_processing(
        self, chat_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MarkMessageProcessingResponse]:
        """
        Marks a message as being processed by a participant. This creates a new processing attempt
        with a system-managed timestamp. The participant must be a member of the chat room.

        This endpoint automatically:
        - Creates a new attempt with auto-incremented attempt_number
        - Sets the attempt status to "processing"
        - Records the started_at timestamp (system-managed)
        - Updates the participant's delivery status to "processing"

        Parameters
        ----------
        chat_id : str
            Chat Room ID

        id : str
            Message ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MarkMessageProcessingResponse]
            Message marked as processing
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/chats/{jsonable_encoder(chat_id)}/messages/{jsonable_encoder(id)}/processing",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MarkMessageProcessingResponse,
                    parse_obj_as(
                        type_=MarkMessageProcessingResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationError,
                        parse_obj_as(
                            type_=ValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
