# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.tool import Tool
from .thenvoi_com_web_api_v_1_tools_controller_index_response_metadata import (
    ThenvoiComWebApiV1ToolsControllerIndexResponseMetadata,
)


class ThenvoiComWebApiV1ToolsControllerIndexResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[Tool]] = None
    metadata: typing.Optional[ThenvoiComWebApiV1ToolsControllerIndexResponseMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
