# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_request import AgentRequest
from ..types.agent_update_request import AgentUpdateRequest
from .raw_client import AsyncRawAgentsClient, RawAgentsClient
from .types.create_agent_response import CreateAgentResponse
from .types.get_agent_response import GetAgentResponse
from .types.list_agent_chats_request_status import ListAgentChatsRequestStatus
from .types.list_agent_chats_request_type import ListAgentChatsRequestType
from .types.list_agent_chats_response import ListAgentChatsResponse
from .types.list_agents_response import ListAgentsResponse
from .types.update_agent_response import UpdateAgentResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentsClient
        """
        return self._raw_client

    def list_agents(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListAgentsResponse:
        """
        Lists agents accessible to the authenticated user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentsResponse
            Agents

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agents.list_agents()
        """
        _response = self._raw_client.list_agents(request_options=request_options)
        return _response.data

    def create_agent(
        self, *, agent: AgentRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAgentResponse:
        """
        Creates a new agent owned by the authenticated user

        Parameters
        ----------
        agent : AgentRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentResponse
            Created Agent

        Examples
        --------
        from thenvoi_client_rest import AgentRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agents.create_agent(
            agent=AgentRequest(
                name="name",
            ),
        )
        """
        _response = self._raw_client.create_agent(agent=agent, request_options=request_options)
        return _response.data

    def list_agent_chats(
        self,
        agents_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        status: typing.Optional[ListAgentChatsRequestStatus] = None,
        type: typing.Optional[ListAgentChatsRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentChatsResponse:
        """
        Lists all chat rooms where the specified agent is a participant

        Parameters
        ----------
        agents_id : str
            Agent ID

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Number of items per page

        status : typing.Optional[ListAgentChatsRequestStatus]
            Filter by status

        type : typing.Optional[ListAgentChatsRequestType]
            Filter by type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentChatsResponse
            Chat Rooms

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agents.list_agent_chats(
            agents_id="agents_id",
            page=1,
            page_size=1,
            status="active",
            type="direct",
        )
        """
        _response = self._raw_client.list_agent_chats(
            agents_id, page=page, page_size=page_size, status=status, type=type, request_options=request_options
        )
        return _response.data

    def get_agent(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetAgentResponse:
        """
        Gets a specific agent by ID if accessible to the authenticated user

        Parameters
        ----------
        id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentResponse
            Agent

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agents.get_agent(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.get_agent(id, request_options=request_options)
        return _response.data

    def update_agent(
        self, id: str, *, agent: AgentUpdateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateAgentResponse:
        """
        Updates an existing agent (supports partial updates)

        Parameters
        ----------
        id : str
            Agent ID

        agent : AgentUpdateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAgentResponse
            Updated Agent

        Examples
        --------
        from thenvoi_client_rest import AgentUpdateRequest, RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agents.update_agent(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            agent=AgentUpdateRequest(),
        )
        """
        _response = self._raw_client.update_agent(id, agent=agent, request_options=request_options)
        return _response.data

    def delete_agent(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Deletes a specific agent if owned by the authenticated user

        Parameters
        ----------
        id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            No Content

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.agents.delete_agent(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.delete_agent(id, request_options=request_options)
        return _response.data


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentsClient
        """
        return self._raw_client

    async def list_agents(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListAgentsResponse:
        """
        Lists agents accessible to the authenticated user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentsResponse
            Agents

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.list_agents()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agents(request_options=request_options)
        return _response.data

    async def create_agent(
        self, *, agent: AgentRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAgentResponse:
        """
        Creates a new agent owned by the authenticated user

        Parameters
        ----------
        agent : AgentRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentResponse
            Created Agent

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AgentRequest, AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.create_agent(
                agent=AgentRequest(
                    name="name",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_agent(agent=agent, request_options=request_options)
        return _response.data

    async def list_agent_chats(
        self,
        agents_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        status: typing.Optional[ListAgentChatsRequestStatus] = None,
        type: typing.Optional[ListAgentChatsRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentChatsResponse:
        """
        Lists all chat rooms where the specified agent is a participant

        Parameters
        ----------
        agents_id : str
            Agent ID

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Number of items per page

        status : typing.Optional[ListAgentChatsRequestStatus]
            Filter by status

        type : typing.Optional[ListAgentChatsRequestType]
            Filter by type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentChatsResponse
            Chat Rooms

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.list_agent_chats(
                agents_id="agents_id",
                page=1,
                page_size=1,
                status="active",
                type="direct",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agent_chats(
            agents_id, page=page, page_size=page_size, status=status, type=type, request_options=request_options
        )
        return _response.data

    async def get_agent(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetAgentResponse:
        """
        Gets a specific agent by ID if accessible to the authenticated user

        Parameters
        ----------
        id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentResponse
            Agent

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.get_agent(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent(id, request_options=request_options)
        return _response.data

    async def update_agent(
        self, id: str, *, agent: AgentUpdateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateAgentResponse:
        """
        Updates an existing agent (supports partial updates)

        Parameters
        ----------
        id : str
            Agent ID

        agent : AgentUpdateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAgentResponse
            Updated Agent

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AgentUpdateRequest, AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.update_agent(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                agent=AgentUpdateRequest(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_agent(id, agent=agent, request_options=request_options)
        return _response.data

    async def delete_agent(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Deletes a specific agent if owned by the authenticated user

        Parameters
        ----------
        id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            No Content

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agents.delete_agent(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_agent(id, request_options=request_options)
        return _response.data
