name: Feature Request
description: Suggest a new feature or enhancement
title: "[Component] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Naming Convention
        Please update the issue title to follow this format:
        `[Component] Brief description`

        **Components:** `[SDK]`, `[Agent]`, `[API]`, `[WebSocket]`, `[Integrations]`, `[Config]`, `[Docs]`, `[CI]`, `[Performance]`

        **Example:** `[Integrations] Add CrewAI support`

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this relate to?
      options:
        - SDK
        - Agent
        - API
        - WebSocket
        - Integrations
        - Config
        - Docs
        - CI
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
