# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .add_chat_participant_request_participant import AddChatParticipantRequestParticipant
    from .add_chat_participant_request_participant_role import AddChatParticipantRequestParticipantRole
    from .add_chat_participant_response import AddChatParticipantResponse
    from .get_available_chat_participants_request_participant_type import (
        GetAvailableChatParticipantsRequestParticipantType,
    )
    from .get_available_chat_participants_response import GetAvailableChatParticipantsResponse
    from .list_chat_participants_request_participant_type import ListChatParticipantsRequestParticipantType
    from .list_chat_participants_response import ListChatParticipantsResponse
    from .remove_chat_participant_response import RemoveChatParticipantResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AddChatParticipantRequestParticipant": ".add_chat_participant_request_participant",
    "AddChatParticipantRequestParticipantRole": ".add_chat_participant_request_participant_role",
    "AddChatParticipantResponse": ".add_chat_participant_response",
    "GetAvailableChatParticipantsRequestParticipantType": ".get_available_chat_participants_request_participant_type",
    "GetAvailableChatParticipantsResponse": ".get_available_chat_participants_response",
    "ListChatParticipantsRequestParticipantType": ".list_chat_participants_request_participant_type",
    "ListChatParticipantsResponse": ".list_chat_participants_response",
    "RemoveChatParticipantResponse": ".remove_chat_participant_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddChatParticipantRequestParticipant",
    "AddChatParticipantRequestParticipantRole",
    "AddChatParticipantResponse",
    "GetAvailableChatParticipantsRequestParticipantType",
    "GetAvailableChatParticipantsResponse",
    "ListChatParticipantsRequestParticipantType",
    "ListChatParticipantsResponse",
    "RemoveChatParticipantResponse",
]
