# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .add_chat_participant_request_participant_role import AddChatParticipantRequestParticipantRole


class AddChatParticipantRequestParticipant(UniversalBaseModel):
    participant_id: str = pydantic.Field()
    """
    Participant ID (User UUID or Agent ID)
    """

    role: AddChatParticipantRequestParticipantRole = pydantic.Field()
    """
    Participant role
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
