# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.tool_request import ToolRequest
from ..types.tool_update_request import ToolUpdateRequest
from .raw_client import AsyncRawToolsClient, RawToolsClient
from .types.thenvoi_com_web_api_v_1_tools_controller_create_response import (
    ThenvoiComWebApiV1ToolsControllerCreateResponse,
)
from .types.thenvoi_com_web_api_v_1_tools_controller_index_response import (
    ThenvoiComWebApiV1ToolsControllerIndexResponse,
)
from .types.thenvoi_com_web_api_v_1_tools_controller_show_response import ThenvoiComWebApiV1ToolsControllerShowResponse
from .types.thenvoi_com_web_api_v_1_tools_controller_update_response import (
    ThenvoiComWebApiV1ToolsControllerUpdateResponse,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawToolsClient
        """
        return self._raw_client

    def thenvoi_com_web_api_v_1_tools_controller_index(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ThenvoiComWebApiV1ToolsControllerIndexResponse:
        """
        Lists tools accessible to the authenticated user with pagination

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Number of items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ThenvoiComWebApiV1ToolsControllerIndexResponse
            Tools

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.tools.thenvoi_com_web_api_v_1_tools_controller_index(
            page=1,
            page_size=1,
        )
        """
        _response = self._raw_client.thenvoi_com_web_api_v_1_tools_controller_index(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def thenvoi_com_web_api_v_1_tools_controller_create(
        self, *, tool: ToolRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ThenvoiComWebApiV1ToolsControllerCreateResponse:
        """
        Creates a new tool owned by the authenticated user

        Parameters
        ----------
        tool : ToolRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ThenvoiComWebApiV1ToolsControllerCreateResponse
            Created Tool

        Examples
        --------
        from thenvoi_client_rest import RestClient, ToolRequest

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.tools.thenvoi_com_web_api_v_1_tools_controller_create(
            tool=ToolRequest(
                description="description",
                name="name",
            ),
        )
        """
        _response = self._raw_client.thenvoi_com_web_api_v_1_tools_controller_create(
            tool=tool, request_options=request_options
        )
        return _response.data

    def thenvoi_com_web_api_v_1_tools_controller_show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ThenvoiComWebApiV1ToolsControllerShowResponse:
        """
        Gets a specific tool by ID if accessible to the authenticated user.

        Returns:
        - 200: Tool found and accessible
        - 404: Tool doesn't exist or is private and not accessible to the user

        Parameters
        ----------
        id : str
            Tool ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ThenvoiComWebApiV1ToolsControllerShowResponse
            Tool

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.tools.thenvoi_com_web_api_v_1_tools_controller_show(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.thenvoi_com_web_api_v_1_tools_controller_show(id, request_options=request_options)
        return _response.data

    def thenvoi_com_web_api_v_1_tools_controller_update(
        self, id: str, *, tool: ToolUpdateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ThenvoiComWebApiV1ToolsControllerUpdateResponse:
        """
        Updates an existing tool (supports partial updates).

        Returns:
        - 200: Successfully updated
        - 403: User can see the tool but lacks permission to modify it (e.g., global tools owned by others)
        - 404: Tool doesn't exist or is private and not accessible to the user
        - 422: Validation errors in the request body

        Parameters
        ----------
        id : str
            Tool ID

        tool : ToolUpdateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ThenvoiComWebApiV1ToolsControllerUpdateResponse
            Updated Tool

        Examples
        --------
        from thenvoi_client_rest import RestClient, ToolUpdateRequest

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.tools.thenvoi_com_web_api_v_1_tools_controller_update(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            tool=ToolUpdateRequest(),
        )
        """
        _response = self._raw_client.thenvoi_com_web_api_v_1_tools_controller_update(
            id, tool=tool, request_options=request_options
        )
        return _response.data

    def thenvoi_com_web_api_v_1_tools_controller_delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Deletes a specific tool if owned by the authenticated user.

        Returns:
        - 204: Successfully deleted
        - 403: User can see the tool but lacks permission to delete it (e.g., global tools owned by others)
        - 404: Tool doesn't exist or is private and not accessible to the user

        Parameters
        ----------
        id : str
            Tool ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            No Content

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.tools.thenvoi_com_web_api_v_1_tools_controller_delete(
            id="daca00d0-eb6b-4db1-8201-c46015c93d04",
        )
        """
        _response = self._raw_client.thenvoi_com_web_api_v_1_tools_controller_delete(
            id, request_options=request_options
        )
        return _response.data


class AsyncToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawToolsClient
        """
        return self._raw_client

    async def thenvoi_com_web_api_v_1_tools_controller_index(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ThenvoiComWebApiV1ToolsControllerIndexResponse:
        """
        Lists tools accessible to the authenticated user with pagination

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Number of items per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ThenvoiComWebApiV1ToolsControllerIndexResponse
            Tools

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.thenvoi_com_web_api_v_1_tools_controller_index(
                page=1,
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.thenvoi_com_web_api_v_1_tools_controller_index(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def thenvoi_com_web_api_v_1_tools_controller_create(
        self, *, tool: ToolRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ThenvoiComWebApiV1ToolsControllerCreateResponse:
        """
        Creates a new tool owned by the authenticated user

        Parameters
        ----------
        tool : ToolRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ThenvoiComWebApiV1ToolsControllerCreateResponse
            Created Tool

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient, ToolRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.thenvoi_com_web_api_v_1_tools_controller_create(
                tool=ToolRequest(
                    description="description",
                    name="name",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.thenvoi_com_web_api_v_1_tools_controller_create(
            tool=tool, request_options=request_options
        )
        return _response.data

    async def thenvoi_com_web_api_v_1_tools_controller_show(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ThenvoiComWebApiV1ToolsControllerShowResponse:
        """
        Gets a specific tool by ID if accessible to the authenticated user.

        Returns:
        - 200: Tool found and accessible
        - 404: Tool doesn't exist or is private and not accessible to the user

        Parameters
        ----------
        id : str
            Tool ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ThenvoiComWebApiV1ToolsControllerShowResponse
            Tool

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.thenvoi_com_web_api_v_1_tools_controller_show(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.thenvoi_com_web_api_v_1_tools_controller_show(
            id, request_options=request_options
        )
        return _response.data

    async def thenvoi_com_web_api_v_1_tools_controller_update(
        self, id: str, *, tool: ToolUpdateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ThenvoiComWebApiV1ToolsControllerUpdateResponse:
        """
        Updates an existing tool (supports partial updates).

        Returns:
        - 200: Successfully updated
        - 403: User can see the tool but lacks permission to modify it (e.g., global tools owned by others)
        - 404: Tool doesn't exist or is private and not accessible to the user
        - 422: Validation errors in the request body

        Parameters
        ----------
        id : str
            Tool ID

        tool : ToolUpdateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ThenvoiComWebApiV1ToolsControllerUpdateResponse
            Updated Tool

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient, ToolUpdateRequest

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.thenvoi_com_web_api_v_1_tools_controller_update(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
                tool=ToolUpdateRequest(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.thenvoi_com_web_api_v_1_tools_controller_update(
            id, tool=tool, request_options=request_options
        )
        return _response.data

    async def thenvoi_com_web_api_v_1_tools_controller_delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Deletes a specific tool if owned by the authenticated user.

        Returns:
        - 204: Successfully deleted
        - 403: User can see the tool but lacks permission to delete it (e.g., global tools owned by others)
        - 404: Tool doesn't exist or is private and not accessible to the user

        Parameters
        ----------
        id : str
            Tool ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            No Content

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tools.thenvoi_com_web_api_v_1_tools_controller_delete(
                id="daca00d0-eb6b-4db1-8201-c46015c93d04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.thenvoi_com_web_api_v_1_tools_controller_delete(
            id, request_options=request_options
        )
        return _response.data
