# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.chat_room import ChatRoom
from .list_my_chats_response_metadata import ListMyChatsResponseMetadata


class ListMyChatsResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[ChatRoom]] = None
    metadata: typing.Optional[ListMyChatsResponseMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
