# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawMyChatsClient, RawMyChatsClient
from .types.list_my_chats_request_status import ListMyChatsRequestStatus
from .types.list_my_chats_response import ListMyChatsResponse


class MyChatsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMyChatsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMyChatsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMyChatsClient
        """
        return self._raw_client

    def list_my_chats(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        status: typing.Optional[ListMyChatsRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyChatsResponse:
        """
        Returns a paginated list of all chat rooms where you are a participant.

        Chat rooms can be filtered by status and include information about your role
        in each room (member, moderator, or admin). The list shows only rooms you have
        access to based on your participation.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number for pagination

        per_page : typing.Optional[int]
            Number of items per page

        status : typing.Optional[ListMyChatsRequestStatus]
            Filter by chat room status (active, archived, or closed)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyChatsResponse
            Chat Rooms

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.my_chats.list_my_chats(
            page=1,
            per_page=1,
            status="active",
        )
        """
        _response = self._raw_client.list_my_chats(
            page=page, per_page=per_page, status=status, request_options=request_options
        )
        return _response.data


class AsyncMyChatsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMyChatsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMyChatsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMyChatsClient
        """
        return self._raw_client

    async def list_my_chats(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        status: typing.Optional[ListMyChatsRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMyChatsResponse:
        """
        Returns a paginated list of all chat rooms where you are a participant.

        Chat rooms can be filtered by status and include information about your role
        in each room (member, moderator, or admin). The list shows only rooms you have
        access to based on your participation.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number for pagination

        per_page : typing.Optional[int]
            Number of items per page

        status : typing.Optional[ListMyChatsRequestStatus]
            Filter by chat room status (active, archived, or closed)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMyChatsResponse
            Chat Rooms

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.my_chats.list_my_chats(
                page=1,
                per_page=1,
                status="active",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_my_chats(
            page=page, per_page=per_page, status=status, request_options=request_options
        )
        return _response.data
