# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.thread import Thread
from .list_my_chat_threads_response_metadata import ListMyChatThreadsResponseMetadata


class ListMyChatThreadsResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[Thread]] = None
    metadata: typing.Optional[ListMyChatThreadsResponseMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
