# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_agent_response import CreateAgentResponse
    from .get_agent_response import GetAgentResponse
    from .list_agent_chats_request_status import ListAgentChatsRequestStatus
    from .list_agent_chats_request_type import ListAgentChatsRequestType
    from .list_agent_chats_response import ListAgentChatsResponse
    from .list_agent_chats_response_metadata import ListAgentChatsResponseMetadata
    from .list_agents_response import ListAgentsResponse
    from .update_agent_response import UpdateAgentResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateAgentResponse": ".create_agent_response",
    "GetAgentResponse": ".get_agent_response",
    "ListAgentChatsRequestStatus": ".list_agent_chats_request_status",
    "ListAgentChatsRequestType": ".list_agent_chats_request_type",
    "ListAgentChatsResponse": ".list_agent_chats_response",
    "ListAgentChatsResponseMetadata": ".list_agent_chats_response_metadata",
    "ListAgentsResponse": ".list_agents_response",
    "UpdateAgentResponse": ".update_agent_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateAgentResponse",
    "GetAgentResponse",
    "ListAgentChatsRequestStatus",
    "ListAgentChatsRequestType",
    "ListAgentChatsResponse",
    "ListAgentChatsResponseMetadata",
    "ListAgentsResponse",
    "UpdateAgentResponse",
]
