# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListAgentChatsResponseMetadata(UniversalBaseModel):
    page: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current page
    """

    page_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of items per page
    """

    total_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of chat rooms
    """

    total_pages: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of pages
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
