# This file was auto-generated by Fern from our API Definition.

import typing

ListChatMessagesRequestMessageType = typing.Union[
    typing.Literal["text", "system", "action", "thought", "guidelines", "error", "tool_call", "tool_result", "task"],
    typing.Any,
]
