# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.chat_message import ChatMessage
from .list_chat_messages_response_metadata import ListChatMessagesResponseMetadata


class ListChatMessagesResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[ChatMessage]] = None
    metadata: typing.Optional[ListChatMessagesResponseMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
