# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.test_response import TestResponse
from .raw_client import AsyncRawTestClient, RawTestClient


class TestClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTestClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTestClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTestClient
        """
        return self._raw_client

    def authentication(self, *, request_options: typing.Optional[RequestOptions] = None) -> TestResponse:
        """
        Advanced test endpoint to verify API access with detailed request information and headers

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestResponse
            Success

        Examples
        --------
        from thenvoi_client_rest import RestClient

        client = RestClient(
            api_key="YOUR_API_KEY",
        )
        client.test.authentication()
        """
        _response = self._raw_client.authentication(request_options=request_options)
        return _response.data


class AsyncTestClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTestClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTestClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTestClient
        """
        return self._raw_client

    async def authentication(self, *, request_options: typing.Optional[RequestOptions] = None) -> TestResponse:
        """
        Advanced test endpoint to verify API access with detailed request information and headers

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestResponse
            Success

        Examples
        --------
        import asyncio

        from thenvoi_client_rest import AsyncRestClient

        client = AsyncRestClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.test.authentication()


        asyncio.run(main())
        """
        _response = await self._raw_client.authentication(request_options=request_options)
        return _response.data
